builds:
  - main: main.go
    binary: edit
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
archive:
  format: tar.gz
  files:
    - README.md
    - LICENSE
    - plugin.yaml
    - scripts/install_plugin.sh
checksum:
  name_template: 'checksums.txt'
